### ISSUE TITLE
What is the meaning of the "Shoup"?

### ISSUE THREAD

**Issue by qxzhou1010** [tlepoint/fhe.rs#187]
hi, first of all a big thanks to `fhe.rs` for this great work, it helped me a lot. However I have some doubts.
In the source code, "shoup"-related names often appear, such as NTTShoup, Shoup multiplication. Is this an optimization algorithm? Are there any papers or materials that can be referred to?

**Comment by tlepoint** [comment]
Hello. 

Good question: this is because we use algorithms put forward by Victor Shoup in the [NTL library](https://libntl.org). This terminology has been used in several papers. See the discussion on page 4 of [this paper](https://arxiv.org/pdf/1205.2926.pdf) for some history about this.

**Comment by qxzhou1010** [comment]
Thanks a lot for your quick reply. In addition, I also have some questions about the algorithms related to **Barrett Reduce**(`lazy_reduce`, `laze_reduce_u128`). I googled and found all kinds of relevant information about Barrett Reduce, but they couldn’t correspond to the implementation of the source code. What are the papers and algorithms you mainly refer to for the implementation of Barrett Reduce?

**Comment by tlepoint** [comment]
I think this is the classical Barrett reduction with `R = 2^128`. They were split here into a "lazy" step that reduces `mod 2p` and a reduction that removes `p` if the result was `>= 2p`. To avoid working with 256-bit numbers, we do the multiplications in 128-bit registers.

**Comment by qxzhou1010** [comment]
Ok, thanks for your patience in answering. My question is that after `barrett` is divided into `barrettLo` and `barrettHi`, I don't understand how the subsequent calculation should be done. I'll do my best to understand this.
