### ISSUE TITLE
Question on correctness of decryption

### ISSUE THREAD

**Issue by samtay** [tlepoint/fhe.rs#216]
Hi :wave:  I've been implementing a prototype of multiparty BFV on top of your library ([here](https://github.com/Sunscreen-tech/fhe.rs/compare/main...Sunscreen-tech:fhe.rs:samtay/threshold) for reference). The public key and relinearization key generated by the multiparty protocols induce quite a bit more noise than the single-key variants, but I've seen some unexpected decryption failures after relinearization, even when using rather large ciphertext moduli (e.g. I've even tried a modulus with ~ `62 * 16` bits). For context, everything works fine if the public key $p = (p_0, p_1)$ used to encrypt the ciphertexts has been generated such that $p_1$ has small coefficients, rather than sampled uniformly from $R_q$, leading me to believe this is an issue related to noise or the handling of large coefficients.

In debugging this, I'm wondering if the issue lies in [`SecretKey::try_decrypt`](https://github.com/tlepoint/fhe.rs/blob/c382f7cbd83cb76e6f6fe5b5b24f5ab7572df2f8/crates/fhe/src/bfv/keys/secret_key.rs#L197), which only reduces the coefficients according to the _first_ ciphertext modulus factor, rather than the entire modulus. However, given a ciphertext modulus $q = q_1 \cdots q_\ell$, plaintext modulus $p$, and coefficient $c$ such that $q_1 < c < q$, it is not necessarily the case that $(c \mod q) \mod p = (c \mod q_1) \mod p$. The LHS is the textbook decryption, while the RHS is the current implementation (if I'm reading correctly).

Curious if I'm missing something or if the current version needs a fix to reduce via the full ciphertext modulus. Thanks for any help!

**Comment by tlepoint** [comment]
Hello. Ah, very interesting. 

So, the decryption operation is not `(c mod q) mod p`, but should be computing `t/Q * (c0 + c1 * s)` (cf. end of page 8 in https://eprint.iacr.org/2021/204.pdf). Here, this is supposedly achieved as follows:
*  Compute the polynomial https://github.com/tlepoint/fhe.rs/blob/c382f7cbd83cb76e6f6fe5b5b24f5ab7572df2f8/crates/fhe/src/bfv/keys/secret_key.rs#L178-L185
* Scaling operation: https://github.com/tlepoint/fhe.rs/blob/c382f7cbd83cb76e6f6fe5b5b24f5ab7572df2f8/crates/fhe/src/bfv/keys/secret_key.rs#L187
* Definition of the scaler: https://github.com/tlepoint/fhe.rs/blob/c382f7cbd83cb76e6f6fe5b5b24f5ab7572df2f8/crates/fhe/src/bfv/parameters.rs#L399-L403

The result should therefore be smaller than the plaintext space (i.e., with your notation, p), and therefore `c mod q0` should be equal to `c mod p`, unless `p` is very close to `q0`. 

Now, I may have missed something... What value of plaintext space are you using? Would you have a minimal example reproducing the bug?

**Comment by samtay** [comment]
Oh, I see. In my comment above, I was considering the coefficient $c$ belonging to the polynomial $c_0 + c_1 s$, however I forgot that scaling happens before reduction modulo $p$, which guarantees coefficients in $\frac{p}{q}(c_0 + c_1 s)$ are indeed smaller than $p$.

In my tests I've just been using the [`BfvParameters::default_arc`](https://github.com/tlepoint/fhe.rs/blob/5c4a80f5a024124a707e4a58e6323a880b99a571/crates/fhe/src/bfv/parameters.rs#L207) function to generate params, which uses a plaintext modulus of `1153`.

I spent some time trying to reproduce this with the `bfv` implementation, but have not succeeded. So, this is likely something wrong on my end with the relinearization key I'm generating in the `mbfv` implementation, and outside the scope of your library. I've actually just noticed that as I increase the ciphertext modulus, my noise measurements actually _increase_ and seem to always exceed the budget. Using the `default_arc(m, 8)` params, and noting that `SecretKey::measure_noise` is a measurement in bits, I think the maximum noise measurement guaranteeing correctness is $\log_2(Q/2t) = \log_2(Q) - \log_2(2) - \log_2(t) = 62m - 1 - 11 =  62m - 12$, and my measurements seem to always exceed this by 1. E.g. for `default_arc(6, 8)` I observe a noise measurement of 361, which exceeds the allowed 360.

In any case, I'll go ahead and close this issue. Thanks for your explanation!

**Comment by samtay** [comment]
Just to follow up, I fixed the problem! I had a missing minus sign :see_no_evil: 

Do let me know if you are ever interested in merging an [implementation](https://github.com/tlepoint/fhe.rs/compare/main...Sunscreen-tech:fhe.rs:samtay/threshold) of [Multiparty BFV](https://eprint.iacr.org/2020/304.pdf) (same version used in lattigo) upstream. I initially intended this to be built as a separate crate, pulling in `fhe.rs` as a dependency, but it would have required exposing too many low level internals outside of the crate.

**Comment by tlepoint** [comment]
Oh this is awesome 🙌🏼, I would be happy to have a version of multiparty BFV in the main repo if you want to do a PR!
